name: Get Package Versions

on: workflow_dispatch

jobs:
  get-packages:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Get package versions
        run: |
          IMAGES=(
            "buerokratt/Buerokratt-Chatbot"
            "buerokratt/Training-Module"
            "buerokratt/Analytics-Module"
            "buerokratt/Service-Module"
            "buerokratt/Chat-Widget"
            "buerokratt/Buerokratt-DSL"
            "buerokratt/Ruuter"
            "buerokratt/DataMapper"
            "buerokratt/Resql"
            "buerokratt/TIM"
            "buerokratt/CronManager"
            "buerokratt/XTR"
            "buerokratt/Authentication-Layer"
            "buerokratt/S3-Ferry"
          )

          # Create or clear the output file
          OUTPUT_FILE="docker_image_tags.txt"
          echo "Docker Image Tags:" > "$OUTPUT_FILE"

          for IMAGE in "${IMAGES[@]}"; do
            echo "Fetching tags for $IMAGE..."

            # Fetch Docker tags using the Docker Registry HTTP API for public repositories
            response=$(curl -s "https://ghcr.io/v2/$IMAGE/tags/list")
            
            # Print the raw response for debugging
            echo "Response for $IMAGE: $response"

            # Check for errors in response
            if echo "$response" | jq -e '.errors' > /dev/null; then
              echo "Error fetching tags for $IMAGE." >> "$OUTPUT_FILE"
              continue
            fi

            # Parse the JSON to list all tags (which are Docker image versions)
            tags=$(echo "$response" | jq -r '.tags[]')

            if [ -n "$tags" ]; then
              echo "Tags for $IMAGE:" >> "$OUTPUT_FILE"
              echo "$tags" >> "$OUTPUT_FILE"
            else
              echo "No tags found for $IMAGE." >> "$OUTPUT_FILE"
            fi
          done

          echo "Docker image tags written to $OUTPUT_FILE."

      - name: Upload docker tags file
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-tags
          path: docker_image_tags.txt
